<?php

declare(strict_types=1);
namespace TrinityBackup\Database\Drivers;

if (!\defined('ABSPATH')) {
    exit;
}

use RuntimeException;
use TrinityBackup\Database\DatabaseInterface;

/**
 * WordPress.org Plugin Check forbids direct mysqli usage.
 * This driver keeps the same interface but delegates to $wpdb.
 */
final class MysqliDriver implements DatabaseInterface
{
    public function connect(): void
    {
        // $wpdb is always available in WordPress runtime.
    }

    public function listTables(): array
    {
        global $wpdb;

        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Listing tables for backup.
        $tables = $wpdb->get_col('SHOW TABLES');

        return array_map('strval', is_array($tables) ? $tables : []);
    }

    public function showCreateTable(string $table): string
    {
        global $wpdb;

        $table = $this->validateIdentifier($table);

        // Identifiers cannot be placeholders; validate strictly instead.
        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQL.NotPrepared, WordPress.DB.DirectDatabaseQuery.SchemaChange, PluginCheck.Security.DirectDB.UnescapedDBParameter -- Table identifier validated via regex, SHOW CREATE TABLE requires literal identifier.
        $row = $wpdb->get_row('SHOW CREATE TABLE `' . $table . '`', ARRAY_A);

        if (!is_array($row) || !isset($row['Create Table'])) {
            throw new RuntimeException('Create statement not found.');
        }

        return (string) $row['Create Table'];
    }

    public function select(string $sql): array
    {
        global $wpdb;

        // Raw SQL is generated by the backup engine.
        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.NotPrepared, PluginCheck.Security.DirectDB.UnescapedDBParameter -- Internal backup query, SQL built by exporter.
        $rows = $wpdb->get_results($sql, ARRAY_A);

        return is_array($rows) ? $rows : [];
    }

    public function execute(string $sql): void
    {
        global $wpdb;

        if ($sql === '') {
            return;
        }

        // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.NotPrepared, PluginCheck.Security.DirectDB.UnescapedDBParameter -- Internal backup/restore query, SQL from backup file.
        $result = $wpdb->query($sql);

        if ($result === false) {
            // phpcs:ignore WordPress.Security.EscapeOutput.ExceptionNotEscaped -- Internal exception message, not output.
            throw new RuntimeException('Query failed: ' . (string) $wpdb->last_error);
        }
    }

    public function escape(string $value): string
    {
        // Do NOT use esc_sql() for SQL dump generation.
        // WordPress applies placeholder escaping which turns "%" into "{hash}", corrupting content.
        // Use a deterministic MySQL-style escape.
        return strtr(
            $value,
            [
                "\x00" => '\\0',
                "\n"   => '\\n',
                "\r"   => '\\r',
                '\\'   => '\\\\',
                "'"    => "\\'",
                '"'    => '\\"',
                "\x1a" => '\\Z',
            ]
        );
    }

    private function validateIdentifier(string $identifier): string
    {
        // Allow common WordPress table identifiers: letters, digits, underscore.
        if (!preg_match('/^[A-Za-z0-9_]+$/', $identifier)) {
            throw new RuntimeException('Invalid table identifier.');
        }

        return $identifier;
    }
}
